import vazirFont from "@/constants/localFonts";
import "../styles/globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} min-h-screen font-sans`}>
        <Header />
        <div className="container xl:max-w-screen-xl"> {children}</div>
      </body>
    </html>
  );
}
