name: Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    if: github.event.label.name == 'auto-pr'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable auto-merge
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
